[package]
name = "img_hash_py"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "img_hash_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.24.2"
image = "0.23"
img_hash = "3"
